name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Package
      run: |
        /opt/unity/Editor/Unity -exportPackage -projectPath dsfdsf -batchmode -nographics
